# Generated by Django 5.0.1 on 2024-01-31 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('BookID', models.IntegerField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=50)),
                ('ISBN', models.CharField(max_length=20, unique=True)),
                ('PublishedDate', models.DateField(null=True)),
                ('Genre', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BookDetails',
            fields=[
                ('DetailsID', models.IntegerField(primary_key=True, serialize=False)),
                ('NumberOfPages', models.IntegerField(null=True)),
                ('Publisher', models.CharField(blank=True, max_length=255)),
                ('Language', models.CharField(blank=True, max_length=50)),
                ('BookID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='libraryapp.book')),
            ],
        ),
        migrations.CreateModel(
            name='BorrowedBooks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BorrowDate', models.DateField(blank=True, null=True)),
                ('ReturnDate', models.DateField(blank=True, null=True)),
                ('BookID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='libraryapp.book')),
                ('UserID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
